pub mod conversion;
pub struct RuleMetadata {
    pub code: &'static str,
    pub category: &'static str,
    pub preview: bool,
    pub help: &'static str,
    pub name: &'static str,
    pub severity: &'static str,
    pub message: &'static str,
    pub explanation: &'static str,
    pub suggestion: &'static str,
    pub details: &'static str,
}
pub static RULES: &[RuleMetadata] = &[
    RuleMetadata {
        code: "T001",
        category: "T",
        preview: false,
        help: "Review whether each batch needs this transfer.",
        name: "transfer-in-loop",
        severity: "medium",
        message: "Potential device transfer inside a loop.",
        explanation: "This conversion may transfer tensor data during each iteration. Static analysis does not measure its cost.",
        suggestion: "Review whether the transfer is necessary for each batch. Move it earlier only if the data and device requirements remain valid.",
        details: include_str!("../../docs/rules/T001.md"),
    },
    RuleMetadata {
        code: "T002",
        category: "T",
        preview: false,
        help: "Review whether both transfers are necessary.",
        name: "device-ping-pong",
        severity: "high",
        message: "Potential device round trip without an intervening use.",
        explanation: "The visible conversion sequence returns this tensor to its starting device without a tracked intermediate use.",
        suggestion: "Review the purpose of both transfers and remove the round trip manually only if its synchronization and data semantics are unnecessary.",
        details: include_str!("../../docs/rules/T002.md"),
    },
    RuleMetadata {
        code: "S001",
        category: "S",
        preview: false,
        help: "Review whether scalar reads can be less frequent.",
        name: "item-in-loop",
        severity: "medium",
        message: "Tensor scalar extraction inside a loop may synchronize with the host.",
        explanation: "Reading a CUDA tensor as a Python scalar may require waiting for device work.",
        suggestion: "Review whether scalar reads can be less frequent or aggregated without changing control flow or logging requirements.",
        details: include_str!("../../docs/rules/S001.md"),
    },
    RuleMetadata {
        code: "S002",
        category: "S",
        preview: false,
        help: "Preserve synchronization required for timing or correctness.",
        name: "explicit-sync",
        severity: "medium",
        message: "Explicit CUDA synchronization may limit asynchronous execution.",
        explanation: "This call waits for CUDA work on the selected device. Its necessity depends on timing and correctness requirements.",
        suggestion: "Review why synchronization is required here before changing it, especially in timing or cross-stream code.",
        details: include_str!("../../docs/rules/S002.md"),
    },
    RuleMetadata {
        code: "D001",
        category: "D",
        preview: false,
        help: "Consider taking the device index from application configuration.",
        name: "hardcoded-device",
        severity: "low",
        message: "CUDA device index is hardcoded.",
        explanation: "A fixed CUDA index may restrict device configuration or portability; it is not inherently a performance defect.",
        suggestion: "Review whether this device index should come from the application's existing configuration.",
        details: include_str!("../../docs/rules/D001.md"),
    },
    RuleMetadata {
        code: "D002",
        category: "D",
        preview: false,
        help: "Review whether this repeated conversion serves an API boundary.",
        name: "repeated-device-cast",
        severity: "low",
        message: "Repeated conversion to the same known device.",
        explanation: "This conversion appears redundant. It may return the existing tensor rather than copying data.",
        suggestion: "Review whether the repeated conversion is needed to express an API boundary or defensive device handling.",
        details: include_str!("../../docs/rules/D002.md"),
    },
    RuleMetadata {
        code: "P001",
        category: "P",
        preview: false,
        help: "Validate numerical requirements before reducing precision.",
        name: "explicit-float64",
        severity: "medium",
        message: "Explicit float64 tensor precision; review whether it is required.",
        explanation: "Float64 is explicitly requested. Its cost and necessity depend on hardware and numerical requirements.",
        suggestion: "Validate numerical accuracy and performance before choosing a lower precision.",
        details: include_str!("../../docs/rules/P001.md"),
    },
    RuleMetadata {
        code: "P002",
        category: "P",
        preview: false,
        help: "Review whether the input dtype can be prepared earlier.",
        name: "repeated-dtype-cast",
        severity: "medium",
        message: "Potential repeated dtype conversion inside a loop.",
        explanation: "This cast may convert tensor values during each iteration. The required input precision is not inferred.",
        suggestion: "Review whether the input dtype can be prepared earlier while preserving numerical behavior and per-batch requirements.",
        details: include_str!("../../docs/rules/P002.md"),
    },
    RuleMetadata {
        code: "S003",
        category: "S",
        name: "tolist-in-loop",
        severity: "medium",
        message: "Tensor.tolist() inside a loop may transfer data to the CPU.",
        explanation: "Tensor.tolist() converts values into Python objects and moves data to the CPU if necessary.",
        suggestion: "Review whether conversion can be performed less frequently.",
        help: "Review whether conversion can be performed less frequently.",
        preview: true,
        details: include_str!("../../docs/rules/S003.md"),
    },
    RuleMetadata {
        code: "S004",
        category: "S",
        name: "scalar-conversion-in-loop",
        severity: "medium",
        message: "Python scalar conversion inside a loop may synchronize with the host.",
        explanation: "Converting a CUDA tensor with bool, int or float may require waiting for device work.",
        suggestion: "Review whether scalar conversion can be performed less frequently.",
        help: "Review whether scalar conversion can be performed less frequently.",
        preview: true,
        details: include_str!("../../docs/rules/S004.md"),
    },
    RuleMetadata {
        code: "S005",
        category: "S",
        name: "nonzero-in-loop",
        severity: "medium",
        message: "CUDA nonzero() inside a loop synchronizes with the host.",
        explanation: "PyTorch nonzero on a CUDA tensor requires host-device synchronization. Static analysis does not measure its cost.",
        suggestion: "Review whether nonzero indices are needed on every iteration.",
        help: "Review whether nonzero indices are needed on every iteration.",
        preview: true,
        details: include_str!("../../docs/rules/S005.md"),
    },
    RuleMetadata {
        code: "M001",
        category: "M",
        name: "empty-cache-in-loop",
        severity: "medium",
        message: "CUDA cache clearing inside a loop may impair allocator reuse.",
        explanation: "empty_cache releases unoccupied cached memory. Repeated clearing may prevent reuse; fragmentation or sharing memory with other applications may justify it.",
        suggestion: "Review whether cache clearing is necessary on every iteration.",
        help: "Review whether cache clearing is necessary on every iteration.",
        preview: true,
        details: include_str!("../../docs/rules/M001.md"),
    },
    RuleMetadata {
        code: "M002",
        category: "M",
        name: "tensor-copy-in-loop",
        severity: "medium",
        message: "Constructing a tensor from a tensor inside a loop copies its data.",
        explanation: "torch.tensor(existing_tensor) creates a new leaf tensor and copies data. The copy and detachment may be intentional.",
        suggestion: "Review whether an independent copy is required on every iteration.",
        help: "Review whether an independent copy is required on every iteration.",
        preview: true,
        details: include_str!("../../docs/rules/M002.md"),
    },
    RuleMetadata {
        code: "M003",
        category: "M",
        name: "accumulating-cat-in-loop",
        severity: "medium",
        message: "Accumulating a tensor with cat inside a loop may repeatedly allocate and copy.",
        explanation: "The visible assignment concatenates the previous accumulator into its replacement. Shapes, iteration counts and runtime cost are unknown.",
        suggestion: "Consider collecting parts and concatenating once if intermediate results are unnecessary.",
        help: "Consider collecting parts and concatenating once if intermediate results are unnecessary.",
        preview: true,
        details: include_str!("../../docs/rules/M003.md"),
    },
    RuleMetadata {
        code: "A001",
        category: "A",
        name: "retain-graph-in-loop",
        severity: "medium",
        message: "Explicit graph retention inside a loop may keep unnecessary autograd state.",
        explanation: "retain_graph=True retains the graph after differentiation. Multiple backward passes may require it.",
        suggestion: "Review graph retention while preserving repeated backward requirements.",
        help: "Review graph retention while preserving repeated backward requirements.",
        preview: true,
        details: include_str!("../../docs/rules/A001.md"),
    },
    RuleMetadata {
        code: "A002",
        category: "A",
        name: "anomaly-detection-enabled",
        severity: "medium",
        message: "Autograd anomaly detection adds debugging overhead.",
        explanation: "Anomaly detection performs additional debugging checks that slow execution. It may be intentional during debugging.",
        suggestion: "Keep anomaly detection enabled when debugging requires it.",
        help: "Keep anomaly detection enabled when debugging requires it.",
        preview: true,
        details: include_str!("../../docs/rules/A002.md"),
    },
];
pub fn metadata(code: &str) -> Option<&'static RuleMetadata> {
    RULES.iter().find(|r| r.code == code)
}
